# Generated by Django 3.2.6 on 2021-08-22 10:42

import commons.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(null=True, upload_to=commons.utils.uuid_name_upload_to),
        ),
    ]
