# Generated by Django 3.2.6 on 2021-08-22 10:49

import commons.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='posts/post/2021/08/22/3c/3c4ced8f55fe4e5899ac2b60c805a', upload_to=commons.utils.uuid_name_upload_to),
            preserve_default=False,
        ),
    ]
