# Generated by Django 3.2.6 on 2021-09-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_alter_plant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='joined',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='last_water',
            field=models.DateField(blank=True, null=True),
        ),
    ]
