# Generated by Django 3.2.6 on 2021-09-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_auto_20210918_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
